GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FydGhpa2EiLCJpYXQiOjE2NTcyNjAyOTd9.L80zyzLe2ZHAhknHLgVdjvD4lD5x4y7ydi80qrjALJo

### create user

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username":"karthika",
    "password":"password",
    "email":"karthika@wbcsoftwarelab.com",
    "age":16,
    "location":"paiyur",
    "domain":"11 std"
}

###login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"soorya@wbcsoftwarelab.com",
    "password":"password"
}

###view send with toaken
GET http://localhost:3000/user/view
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29vcnlhIiwiZW1haWwiOiJzb29yeWFAd2Jjc29mdHdhcmVsYWIuY29tIiwiYWdlIjoyMywibG9jYXRpb24iOiJ0aGlydXBwYXRodXIiLCJkb21haW4iOiJEZXZlbG9wZXIiLCJpYXQiOjE2NTczNDMzNDB9.t7KDjfGSxg9BeHyPCkOPYsdatUFStxN-T70GanGTw0E"
  
}