GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2FydGhpa2EiLCJpYXQiOjE2NTcyNjAyOTd9.L80zyzLe2ZHAhknHLgVdjvD4lD5x4y7ydi80qrjALJo

###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username":"karthika",
    "password":"password",
    "email":"karthika@wbcsoftwarelab.com",
    "age":16,
    "location":"paiyur",
    "domain":"11 std"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"karthika@wbcsoftwarelab.com",
    "password":"password"
}

###
GET http://localhost:3000/user/view
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2FydGhpa2EiLCJlbWFpbCI6ImthcnRoaWthQHdiY3NvZnR3YXJlbGFiLmNvbSIsImFnZSI6MTYsImxvY2F0aW9uIjoicGFpeXVyIiwiZG9tYWluIjoiMTEgc3RkIiwiaWF0IjoxNjU3MjgyNzQzfQ.rWGnHLiuvxI9Qk5wqbdXklo7ZwCiPEWyfwMy9Z2sRNg"
  
}